kind: Deployment
apiVersion: apps/v1
metadata:
  name: cicd-demo-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo-react
  template:
    metadata:
      labels:
        app: cicd-demo-react
    spec:
      containers:
      - name: cicd-demo-react
        image: chefdigitaldemo/cicd-demo-react:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "300m"
          limits:
            memory: "200Mi"
            cpu: "600m"
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: cicd-demo-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: cicd-demo-react